---
input_file: ./README.md
output_directory: ./slides
output_filename: slide
reveal:
  template:
  template_color: FFFFFF
  intro:
  intro_title: Git 
  intro_author: IMAPEX 
  intro_color: 049FD9
  closing:
  closing_message: Thank you!
  closing_color: 049FD9
